export const CALCULATOR_DIGIT_BUTTON_CLICK = "CALCULATOR_DIGIT_BUTTON_CLICK";
export const CALCULATOR_SIGN_BUTTON_CLICK = "CALCULATOR_SIGN_BUTTON_CLICK";
// export const CALCULATOR_BUTTON_CLICK = "CALCULATOR_BUTTON_CLICK";
